from launch import LaunchDescription
from launch_ros.actions import Node
import os

def generate_launch_description():

    #pkg_name = 'lexus_bringup'
    #pkg_dir = os.popen('/bin/bash -c "source /usr/share/colcon_cd/function/colcon_cd.sh && colcon_cd %s && pwd"' % pkg_name).read().strip()


    return LaunchDescription([
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='golf_f_tf',
            output='screen',
            arguments=['2.0', '4.0', '0.31623','0.0', '0.0', '0.0','map','fake_golf'],
        ),
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='drone_f_tf',
            output='screen',
            arguments=['1.0', '2.5', '1.2','3.14159', '0.0', '0.0','map','fake_drone'],
        ),
         Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='lexus_f_tf',
            output='screen',
            arguments=['2.0', '0.0', '0.325','0.0', '0.0', '0.0','map','fake_lexus'],
        ),
         Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='nissan_f_tf',
            output='screen',
            arguments=['2.0', '-3.0', '0.31623','0.0', '0.0', '0.0','map','fake_nissan'],
        ),
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='rosbot_f_tf',
            output='screen',
            arguments=['6.5', '0.5', '0.04','0.0', '0.0', '0.0', 'map','fake_rosbot'],
        ),
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='turtlecar_f_tf',
            output='screen',
            arguments=['6.5', '-0.5', '0.04','0.0', '0.0', '0.0', 'map','fake_turtlecar'],
        ),
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='loomo_f_tf',
            output='screen',
            arguments=['6.5', '0.0', '0.105','0.0', '0.0', '0.0','map','fake_loomo'],
        ),
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='stopbase_f_tf',
            output='screen',
            arguments=['5.0', '2.0', '1.0','0.0', '0.0', '0.0','map','fake_stopbase'],
        ),
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='stopletters_f_tf',
            output='screen',
            arguments=['5.0', '2.0', '1.0','0.0', '0.0', '0.0', 'map','fake_stopletters'],
        ),
        Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='cone_f_tf',
            output='screen',
            arguments=['6.0', '2.0', '0.0','0.0', '0.0', '0.0','map','fake_cone'],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='drone',
            name='drone_f',
            output='screen',
            parameters=[{"drone_frame_id":'fake_drone'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='stopletters',
            name='stopletters_f',
            output='screen',
            parameters=[{"stopletters_frame_id":'fake_stopletters'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='cone',
            name='cone_f',
            output='screen',
            parameters=[{"cone_frame_id":'fake_cone'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='egolf',
            name='golf_f',
            output='screen',
            parameters=[{"golf_frame_id":'fake_golf'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='lexus',
            name='lexus_f',
            output='screen',
            parameters=[{"lexus_frame_id":'fake_lexus'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='loomo',
            name='loomo_f',
            output='screen',
            parameters=[{"loomo_frame_id":'fake_loomo'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='nissan',
            name='nissan_f',
            output='screen',
            parameters=[{"nissan_frame_id":'fake_nissan'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='rosbot',
            name='rosbot_f',
            output='screen',
            parameters=[{"rosbot_frame_id":'fake_rosbot'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='stopbase',
            name='stopbase_f',
            output='screen',
            parameters=[{"stopbase_frame_id":'fake_stopbase'}],
        ),
        Node(
            package='rviz_markers',
            #namespace='lexus3',
            executable='turtlecar',
            name='turtlecar_f',
            output='screen',
            parameters=[{"turtlecar_frame_id":'fake_turtlecar'}],
        ),
         Node(
            package='tf2_ros',
            #namespace='lexus3',
            executable='static_transform_publisher',
            name='map',
            output='screen',
            arguments=['0.0', '0.0', '0.0','0.0', '0.0', '0.0','base_link', 'map'],
        )
    ])